#!/bin/bash

# Get parameters function
# This function will check all the parameters 
# Return:
#   string: params to run the server
#   int: -1 is something is wrong.

getparams() {
    # Basic + default params values:
    #   -nographics: basic param for the valheim documentation. MANDATORY.
    #   -batchmode: bacic param for the valheim documentation. MANDATORY.
    #   -public: used the value of the param if defined, if not it will be a private server (0) MANDATORY.
    #   -port: used the value of the param if defined, if not it will use standard port (2456) MANDATORY.
    params="-console +map _server_start +maxplayers 12"
    params="$params -port ${PORT:-27015}"
}

# Main function
main() {
    # Basic export for the BOX64 emulator
    echo "##############################"
    echo "Basic variables running box64:"
    echo "BOX64_LD_LIBRARY_PATH: ${BOX64_LD_LIBRARY_PATH}"
    echo "BOX64_LOG: ${BOX64_LOG}"
    echo "BOX64_TRACE_FILE: ${BOX64_TRACE_FILE}"
    echo "BOX64_TRACE: ${BOX64_TRACE}"
    echo "##############################"

    # Part of the standar code startup of the server:
    export templdpath="${LD_LIBRARY_PATH}"
    export LD_LIBRARY_PATH=./linux:./linux32:"${LD_LIBRARY_PATH}"
    export SteamAppId=${STEAMAPPID}
    
    # Move to the execution folder
    cd /root/svends

    ## Checking the final parameters to use:
    echo "##############################"
    echo "Final SvenDS parameters to run: $params"
    echo "##############################"

    # Starting the server:
    box86 ./SvenDS $params
}

getparams
main
